name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Login to OCIR
      uses: docker/login-action@v1
      with:
        registry: ap-seoul-1.ocir.io
        username: ${{ secrets.OCI_USERNAME }}
        password: ${{ secrets.OCI_TOKEN }} 
